### ISSUE TITLE
Signal maps stop working with an OOME thrown requiring restart to fix

### ISSUE THREAD

**Issue by peter-mount** [peter-mount/opendata#20]
There was a crash this morning. Interestingly looking at the logs it runs with ~4.7k-4.9k messages a minute then drops to less than half and then nothing.

Sounds like a deadlock of some kind, however the oom is then in tomcat's Nio code which could be a big download is stuck.

here's the tomcat log
```
05-May-2015 08:53:00.239 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4956
05-May-2015 08:53:42.116 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.cache.Cache.expireByAge Expired 3 entries. Now have 6
05-May-2015 08:53:42.116 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.cache.Cache.expireByAge Expired 2 entries. Now have 6
05-May-2015 08:53:42.116 INFO [Open-Data-DaemonThread-7] null.null Expired 2 entries. Now have 6
05-May-2015 08:54:00.239 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4768
05-May-2015 08:54:32.599 WARNING [http-nio-2a01:7e00:0:0:f03c:91ff:fe84:5257-8080-exec-2] uk.trainwatch.gis.StationPositionManager.lambda$new$25 Center StationPosition[
name="FAIRBOURNE", tiploc="FRBN", lat="52.6958542", long="-4.04915285", distance=0.043476] Range 0.043476 returning [StationPosition[name="MORFA MAWDDACH", tiploc="MFAM
", lat="52.7072792", long="-4.03173256", distance=1.0747555541180687], StationPosition[name="BARMOUTH", tiploc="BRMOUTH", lat="52.7221985", long="-4.05642986", distance
=1.8455289237575505], StationPosition[name="LLWYNGWRIL", tiploc="LYNGRIL", lat="52.6666145", long="-4.08792257", distance=2.5920605506621643]]
05-May-2015 08:54:42.116 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:54:42.116 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:54:42.116 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:55:00.239 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4608
05-May-2015 08:55:42.116 INFO [Open-Data-DaemonThread-7] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:55:42.116 INFO [Open-Data-DaemonThread-14] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:55:42.116 INFO [Open-Data-DaemonThread-14] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 7
05-May-2015 08:56:00.239 INFO [Open-Data-DaemonThread-14] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4608
05-May-2015 08:56:42.116 INFO [Open-Data-DaemonThread-1] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 6
05-May-2015 08:56:42.116 INFO [Open-Data-DaemonThread-7] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 6
05-May-2015 08:56:42.116 INFO [Open-Data-DaemonThread-7] uk.trainwatch.util.cache.Cache.expireByAge Expired 1 entries. Now have 6
05-May-2015 08:56:43.756 INFO [http-nio-2a01:7e00:0:0:f03c:91ff:fe84:5257-8080-exec-15] uk.trainwatch.web.map.cache.ImageCache.render Retrieving: http://ganymede.area51
.onl:9080/geoserver/gwc/service/tms/1.0.0/osgb_rail@EPSG:900913@png/15/16302/22103.png
05-May-2015 08:56:43.808 INFO [http-nio-2a01:7e00:0:0:f03c:91ff:fe84:5257-8080-exec-15] uk.trainwatch.web.map.cache.ImageCache.render Retrieved 4960 from http://ganymed
e.area51.onl:9080/geoserver/gwc/service/tms/1.0.0/osgb_rail@EPSG:900913@png/15/16302/22103.png
05-May-2015 08:57:00.239 INFO [Open-Data-DaemonThread-7] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4800
05-May-2015 08:58:00.737 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 4736
05-May-2015 08:59:01.784 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.counter.RateMonitor.lambda$new$60 Receive nr.td.area.# 1535
Exception in thread "MyScheduler_QuartzSchedulerThread" 05-May-2015 09:00:06.056 INFO [Open-Data-DaemonThread-7] null.null Expired 1 entries. Now have 5
05-May-2015 09:01:40.270 INFO [Open-Data-DaemonThread-7] uk.trainwatch.util.cache.Cache.expireByAge Expired 2 entries. Now have 3
05-May-2015 09:01:40.269 INFO [Open-Data-DaemonThread-1] null.null Receive nr.td.area.# 1
05-May-2015 09:01:18.333 INFO [Open-Data-DaemonThread-6] null.null Expired 1 entries. Now have 5
05-May-2015 09:01:40.270 INFO [Open-Data-DaemonThread-6] uk.trainwatch.util.cache.Cache.expireByAge Expired 2 entries. Now have 3
05-May-2015 08:59:51.693 INFO [Open-Data-DaemonThread-14] null.null Expired 1 entries. Now have 5
05-May-2015 09:01:40.270 INFO [Open-Data-DaemonThread-14] uk.trainwatch.util.cache.Cache.expireByAge Expired 2 entries. Now have 3
05-May-2015 09:01:41.437 SEVERE [http-nio-2a01:7e00:0:0:f03c:91ff:fe84:5257-8080-ClientPoller-1] org.apache.tomcat.util.net.NioEndpoint$Poller.run 
 java.lang.OutOfMemoryError: Java heap space
        at org.apache.tomcat.util.net.NioEndpoint.reclaimParachute(NioEndpoint.java:310)
        at org.apache.tomcat.util.net.NioEndpoint.checkParachute(NioEndpoint.java:295)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:1102)
        at java.lang.Thread.run(Thread.java:745)

java.lang.OutOfMemoryError: Java heap space
        at org.quartz.CronExpression.getTimeAfter(CronExpression.java:1163)
        at org.quartz.impl.triggers.CronTriggerImpl.getTimeAfter(CronTriggerImpl.java:834)
        at org.quartz.impl.triggers.CronTriggerImpl.getFireTimeAfter(CronTriggerImpl.java:539)
        at org.quartz.impl.triggers.CronTriggerImpl.triggered(CronTriggerImpl.java:715)
        at org.quartz.simpl.RAMJobStore.triggersFired(RAMJobStore.java:1505)
05-May-2015 09:01:41.438 SEVERE [http-nio-2a01:7e00:0:0:f03c:91ff:fe84:5257-8080-exec-7] org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun 
 java.lang.OutOfMemoryError: Java heap space
        at sun.util.resources.TimeZoneNames.getContents(TimeZoneNames.java:279)
        at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:137)
        at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
        at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
        at java.util.ResourceBundle.containsKey(ResourceBundle.java:1807)
        at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:262)
```

Apache does see this post crash:
```
[Tue May 05 09:01:41 2015] [error] [client 207.46.13.149] (20014)Internal error: proxy: error reading status line from remote server janus:8080
[Tue May 05 09:01:41 2015] [error] [client 207.46.13.149] proxy: Error reading from remote server returned by /robots.txt
[Tue May 05 09:02:55 2015] [error] [client 207.46.13.149] (70007)The timeout specified has expired: proxy: error reading status line from remote server janus:8080
```

That said there's some interesting search bot traffic at the time of the crash:
```
207.46.13.119 - - [05/May/2015:08:56:01 +0000] "GET /LEW HTTP/1.1" 404 803 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
66.249.65.135 - - [05/May/2015:08:57:30 +0000] "GET /index.php?title=Denmark_Hill_railway_station&action=edit&redlink=1 HTTP/1.1" 404 813 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
207.46.13.149 - - [05/May/2015:08:57:53 +0000] "GET /station/STRHCOM HTTP/1.1" 302 310 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:53 +0000] "GET /robots.txt HTTP/1.1" 502 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:39 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:29 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:34 +0000] "GET /index.php?title=Special:Upload&wpDestFile=BSicon_%C3%9CWo%2Bl.svg HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:09:00:02 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:44 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:35 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:31 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:49 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:44 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:34 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:56 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:59:57 +0000] "GET /robots.txt HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
207.46.13.149 - - [05/May/2015:08:57:55 +0000] "GET /station/SRC HTTP/1.1" 502 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
66.249.65.131 - - [05/May/2015:09:00:27 +0000] "GET /timetable/station/CARMYLE HTTP/1.1" 502 581 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
68.180.228.59 - - [05/May/2015:09:01:18 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
68.180.228.59 - - [05/May/2015:09:01:49 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
68.180.228.59 - - [05/May/2015:09:02:20 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
207.46.13.119 - - [05/May/2015:09:02:43 +0000] "GET /index.php?title=Special:Upload&wpDestFile=BSicon_STRq.svg HTTP/1.1" 502 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
68.180.228.59 - - [05/May/2015:09:02:51 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
68.180.228.59 - - [05/May/2015:09:03:22 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
68.180.228.59 - - [05/May/2015:09:03:53 +0000] "GET /Canterbury_West_Rail_Station HTTP/1.1" 502 528 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
180.76.5.67 - - [05/May/2015:09:05:02 +0000] "GET /station/BLNDLAC HTTP/1.1" 502 536 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
```

**Comment by peter-mount** [comment]
Still not found this but as a temporary fix tomcat is restarted daily around 0300 each morning. Since then it's not happened again so there's definitely a memory leak somewhere.
